/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package freimapgsoc;

import javax.swing.JPanel;
import org.openide.util.NbPreferences;

public final class FreimapVisualPanel4 extends JPanel {

    /** Creates new form FreimapVisualPanel4 */
    public FreimapVisualPanel4() {
        initComponents();
        hostText.setText(NbPreferences.forModule(FreimapWizardPanel2.class).get("host", "/etc/olsrdDEF.conf"));
        databaseText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("dbText", "freimapDEF"));
        portText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("port", "3306DEF"));
        usernameText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("username", "rootDEF"));
        passwordText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("password", "DEF"));
        nameServiceText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("nameServicePath", "/var/run/latlon.jsDEF"));
        dotDrawText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("dotDrawPort", "2004DEF"));
        olsrdText.setText(NbPreferences.forModule(FreimapVisualPanel2.class).get("olsrdPath", "/etc/olsrd.confDEF"));
    }

    @Override
    public String getName() {
        return "Completed Wizard";
    }

   public String getHost() {
        return hostText.getText();
    }

     public String getPort() {
        return portText.getText();
    }

      public String getDatabase() {
        return databaseText.getText();
    }

       public String getUserName() {
        return usernameText.getText();
    }

        public String getPassword() {
        return passwordText.getText();
    }

        public String getOlsrdPath(){
            return olsrdText.getText();
        }

        public String getDotDrawPort(){
            return dotDrawText.getText();
        }

        public String getNameServicePath(){
            return nameServiceText.getText();
        }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hostText = new javax.swing.JTextField();
        databaseText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        olsrdText = new javax.swing.JTextField();
        nameServiceText = new javax.swing.JTextField();
        dotDrawText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        portText = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel7.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel3.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel5.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel6.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel8.text")); // NOI18N

        hostText.setEditable(false);
        hostText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.hostText.text")); // NOI18N
        hostText.setEnabled(false);

        databaseText.setEditable(false);
        databaseText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.databaseText.text")); // NOI18N
        databaseText.setEnabled(false);

        usernameText.setEditable(false);
        usernameText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.usernameText.text")); // NOI18N
        usernameText.setEnabled(false);

        passwordText.setEditable(false);
        passwordText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.passwordText.text")); // NOI18N
        passwordText.setEnabled(false);

        olsrdText.setEditable(false);
        olsrdText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.olsrdText.text")); // NOI18N
        olsrdText.setEnabled(false);

        nameServiceText.setEditable(false);
        nameServiceText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.nameServiceText.text")); // NOI18N
        nameServiceText.setEnabled(false);

        dotDrawText.setEditable(false);
        dotDrawText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.dotDrawText.text")); // NOI18N
        dotDrawText.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.jLabel9.text")); // NOI18N

        portText.setEditable(false);
        portText.setText(org.openide.util.NbBundle.getMessage(FreimapVisualPanel4.class, "FreimapVisualPanel4.portText.text")); // NOI18N
        portText.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(passwordText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dotDrawText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nameServiceText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(olsrdText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(hostText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(databaseText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(usernameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9)
                                .add(10, 10, 10)
                                .add(portText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 315, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel7)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(hostText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(databaseText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(usernameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(portText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(passwordText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(olsrdText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(nameServiceText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(dotDrawText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField databaseText;
    private javax.swing.JTextField dotDrawText;
    private javax.swing.JTextField hostText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameServiceText;
    private javax.swing.JTextField olsrdText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField portText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}

