/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on 9-nov-2009, 19.44.22
 */

package freimapgsoc;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author stefanopilla
 */
public class Start extends javax.swing.JFrame {

    /** Creates new form Start */
    public Start() {
        initComponents();
        CheckActiveDataSource check=new CheckActiveDataSource();
        if(check.mySql){
           mySQLButton.setEnabled(true);
        }
        if(check.nameservice){
            nameServiceButton.setEnabled(true);
        }
        if(check.olsr){
            olsrdButton.setEnabled(true);
        }
        if(!check.mySql&&!check.nameservice&&!check.olsr){
            firstLabel.setText("There aren't Live DataSources");
            secondLabel.setText("please choose a file.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        olsrdButton = new javax.swing.JButton();
        mySQLButton = new javax.swing.JButton();
        nameServiceButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Start.class);
        olsrdButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        olsrdButton.setText(resourceMap.getString("olsrdButton.text")); // NOI18N
        olsrdButton.setEnabled(false);
        olsrdButton.setName("olsrdButton"); // NOI18N
        olsrdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olsrdButtonActionPerformed(evt);
            }
        });

        mySQLButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        mySQLButton.setText(resourceMap.getString("mySQLButton.text")); // NOI18N
        mySQLButton.setEnabled(false);
        mySQLButton.setName("mySQLButton"); // NOI18N

        nameServiceButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        nameServiceButton.setText(resourceMap.getString("nameServiceButton.text")); // NOI18N
        nameServiceButton.setEnabled(false);
        nameServiceButton.setName("nameServiceButton"); // NOI18N
        nameServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameServiceButtonActionPerformed(evt);
            }
        });

        openFileButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        openFileButton.setText(resourceMap.getString("openFileButton.text")); // NOI18N
        openFileButton.setName("openFileButton"); // NOI18N
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("secondLabel.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        firstLabel.setFont(resourceMap.getFont("secondLabel.font")); // NOI18N
        firstLabel.setText(resourceMap.getString("firstLabel.text")); // NOI18N
        firstLabel.setName("firstLabel"); // NOI18N

        secondLabel.setFont(resourceMap.getFont("secondLabel.font")); // NOI18N
        secondLabel.setText(resourceMap.getString("secondLabel.text")); // NOI18N
        secondLabel.setName("secondLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(openFileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(mySQLButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(olsrdButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(nameServiceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(secondLabel)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(firstLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondLabel)
                .addGap(34, 34, 34)
                .addComponent(olsrdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameServiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mySQLButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openFileButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void olsrdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olsrdButtonActionPerformed
        //new Layer(new OlsrdDataSource().init());
        this.dispose();

    }//GEN-LAST:event_olsrdButtonActionPerformed

    private void nameServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameServiceButtonActionPerformed
    new Layer(new LatLonJsDataSource().init("/var/run/latlon.js"));
    }//GEN-LAST:event_nameServiceButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
    JFileChooser fc= new JFileChooser();
            fc.addChoosableFileFilter(new xmlFileFilter());
            fc.addChoosableFileFilter(new jsFileFilter());
            //fc.addChoosableFileFilter(new FmpFileFilter());
            fc.setAcceptAllFileFilterUsed(false);
            int returnVal = fc.showOpenDialog(fc);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                String extension = Utils.getExtension(file);
                            if (extension.equals(Utils.xml)){
//                                new Layer(new xmlDataSource().init(null));
                            }
                            if (extension.equals(Utils.js)){
                             new Layer(new LatLonJsDataSource().init("file://"+file.getPath()));
                            }
                // FileMenu fm=new FileMenu();
                 //fm.addRecentFile(file.getPath(), file.getName());
            } else if (returnVal == JFileChooser.CANCEL_OPTION) {
                System.out.println("Open command cancelled by user." + "\n");
            }        // TODO add your handling code here:
    }//GEN-LAST:event_openFileButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mySQLButton;
    private javax.swing.JButton nameServiceButton;
    private javax.swing.JButton olsrdButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JLabel secondLabel;
    // End of variables declaration//GEN-END:variables

}
