/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on 9-nov-2009, 19.44.22
 */
package freimapgsoc;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author stefanopilla
 */
public class Start extends javax.swing.JFrame {

    /** Creates new form Start */
    public Start() {
        initComponents();
        CheckActiveDataSource check = new CheckActiveDataSource();
        if (check.mySql) {
            mySQLButton.setEnabled(true);
        }
        if (check.nameservice) {
            nameServiceButton.setEnabled(true);
        }
        if (check.olsr) {
            olsrdButton.setEnabled(true);
        }
        //if (!check.mySql && !check.nameservice && !check.olsr) {
         //   firstLabel.setText("There aren't DataSources");
        //}
    }

    /**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 * @return 
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        olsrdButton = new javax.swing.JButton();
        mySQLButton = new javax.swing.JButton();
        nameServiceButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        secondLabel = new javax.swing.JLabel();
        openExampleFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Start.class);
        olsrdButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        olsrdButton.setText(resourceMap.getString("olsrdButton.text")); // NOI18N
        olsrdButton.setEnabled(false);
        olsrdButton.setName("olsrdButton"); // NOI18N
        olsrdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olsrdButtonActionPerformed(evt);
            }
        });

        mySQLButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        mySQLButton.setText(resourceMap.getString("mySQLButton.text")); // NOI18N
        mySQLButton.setEnabled(false);
        mySQLButton.setName("mySQLButton"); // NOI18N
        mySQLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySQLButtonActionPerformed(evt);
            }
        });

        nameServiceButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        nameServiceButton.setText(resourceMap.getString("nameServiceButton.text")); // NOI18N
        nameServiceButton.setEnabled(false);
        nameServiceButton.setName("nameServiceButton"); // NOI18N
        nameServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameServiceButtonActionPerformed(evt);
            }
        });

        openFileButton.setFont(resourceMap.getFont("nameServiceButton.font")); // NOI18N
        openFileButton.setText(resourceMap.getString("openFileButton.text")); // NOI18N
        openFileButton.setName("openFileButton"); // NOI18N
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        secondLabel.setFont(resourceMap.getFont("secondLabel.font")); // NOI18N
        secondLabel.setText(resourceMap.getString("secondLabel.text")); // NOI18N
        secondLabel.setName("secondLabel"); // NOI18N

        openExampleFile.setFont(resourceMap.getFont("openExampleFile.font")); // NOI18N
        openExampleFile.setText(resourceMap.getString("openExampleFile.text")); // NOI18N
        openExampleFile.setName("openExampleFile"); // NOI18N
        openExampleFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openExampleFileActionPerformed(evt);
            }
        });

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(olsrdButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameServiceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mySQLButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openExampleFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openFileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(secondLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(secondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(olsrdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameServiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mySQLButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openFileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openExampleFile)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void olsrdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olsrdButtonActionPerformed
        //new Layer(new OlsrdDataSource().init());
        this.dispose();

    }//GEN-LAST:event_olsrdButtonActionPerformed

    private void nameServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameServiceButtonActionPerformed
        //new Layer(new LatLonJsDataSource().init("/var/run/latlon.js"));
    }//GEN-LAST:event_nameServiceButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new xmlFileFilter());
        fc.addChoosableFileFilter(new jsFileFilter());
        //fc.addChoosableFileFilter(new FmpFileFilter());
        fc.setAcceptAllFileFilterUsed(false);
        int returnVal = fc.showOpenDialog(fc);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String extension = Utils.getExtension(file);
            if (extension.equals(Utils.xml)) {
//                                new Layer(new xmlDataSource().init(null));
            }
            if (extension.equals(Utils.js)) {
                new LatLonJsDataSource().init("file://" + file.getPath());
                this.dispose();

            }
            // FileMenu fm=new FileMenu();
            //fm.addRecentFile(file.getPath(), file.getName());
        } else if (returnVal == JFileChooser.CANCEL_OPTION) {
            System.out.println("Open command cancelled by user." + "\n");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void openExampleFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openExampleFileActionPerformed
        new LatLonJsDataSource().init("file:///Users/Stefano/Desktop/FreimapSte/Freimap/hg/src/data/latlon.js");
        this.dispose();

    }//GEN-LAST:event_openExampleFileActionPerformed

    private void mySQLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySQLButtonActionPerformed
        new CredentialRequired().setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mySQLButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Start().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mySQLButton;
    private javax.swing.JButton nameServiceButton;
    private javax.swing.JButton olsrdButton;
    private javax.swing.JButton openExampleFile;
    private javax.swing.JButton openFileButton;
    private javax.swing.JLabel secondLabel;
    // End of variables declaration//GEN-END:variables
}
